import { SkillItem, SkillType } from "assets/types/app";

export const skills: Array<SkillItem> = [
  {
    name: "Composer",
    type: SkillType.BACKEND,
    image: "composer.svg",
    select: true,
  },
  {
    name: "Css",
    type: SkillType.FRONTEND,
    image: "css.svg",
    select: true,
  },
  {
    name: "Git",
    type: SkillType.TOOLS,
    image: "github.svg",
    select: true,
  },
  {
    name: "Gulp",
    type: SkillType.TOOLS,
    image: "gulp.svg",
    select: true,
  },
  {
    name: "Html",
    type: SkillType.FRONTEND,
    image: "html.svg",
    select: true,
  },
  {
    name: "Jest",
    type: SkillType.TOOLS,
    image: "jest.svg",
    select: true,
  },
  {
    name: "Joomla",
    type: SkillType.BACKEND,
    image: "joomla.svg",
    select: true,
  },
  {
    name: "jQuery",
    type: SkillType.FRONTEND,
    image: "jquery.svg",
    select: true,
  },
  {
    name: "Js",
    type: SkillType.FRONTEND,
    image: "js.svg",
    select: true,
  },
  {
    name: "Laravel",
    type: SkillType.BACKEND,
    image: "laravel.svg",
    select: true,
  },
  {
    name: "MySql",
    type: SkillType.BACKEND,
    image: "mysql.svg",
    select: true,
  },
  {
    name: "npm",
    type: SkillType.TOOLS,
    image: "npm.svg",
    select: true,
  },
  {
    name: "Nuxt",
    type: SkillType.FRONTEND,
    image: "nuxt.svg",
    select: true,
  },
  {
    name: "Penia",
    type: SkillType.FRONTEND,
    image: "penia.svg",
    select: true,
  },
  {
    name: "Php",
    type: SkillType.BACKEND,
    image: "php.svg",
    select: true,
  },
  {
    name: "Prettier",
    type: SkillType.TOOLS,
    image: "prettier.svg",
    select: true,
  },
  {
    name: "React",
    type: SkillType.FRONTEND,
    image: "react.svg",
    select: true,
  },
  {
    name: "Redux",
    type: SkillType.FRONTEND,
    image: "redux.svg",
    select: true,
  },
  {
    name: "Sass",
    type: SkillType.FRONTEND,
    image: "sass.svg",
    select: true,
  },
  {
    name: "Tailwind",
    type: SkillType.FRONTEND,
    image: "tailwind.svg",
    select: true,
  },
  {
    name: "Ts",
    type: SkillType.FRONTEND,
    image: "ts.svg",
    select: true,
  },
  {
    name: "Vite",
    type: SkillType.TOOLS,
    image: "vite.svg",
    select: true,
  },
  {
    name: "Vitest",
    type: SkillType.TOOLS,
    image: "vitest.svg",
    select: true,
  },
  {
    name: "Vue",
    type: SkillType.FRONTEND,
    image: "vue.svg",
    select: true,
  },
  {
    name: "Webpack",
    type: SkillType.TOOLS,
    image: "webpack.svg",
    select: true,
  },
  {
    name: "Wordpress",
    type: SkillType.BACKEND,
    image: "wordpress.svg",
    select: true,
  },
];
